/**
 * Project Generalized Stochastic Differential Equations Solver
 * @author Santiago Nunez-Corrales
 * @version 0.1
 */


#ifndef _UNARYOPERATOR_H
#define _UNARYOPERATOR_H

enum UnaryOperator { UOP_SIN, UOP_COS, UOP_TAN, UOP_CSC, UOP_SEC, UOP_COT, UOP_SINH, UOP_COSH, UOP_TANH, UOP_CSCH, UOP_SECH, UOP_COTH, UOP_ASIN, UOP_ACOS, UOP_ATAN, UOP_ACSC, UOP_ASEC, UOP_ACOT, UOP_ASENH, UOP_ACOSH, UOP_ATANH, UOP_ACSCH, UOP_ASECH, UOP_ACOTH, UOP_EXP, UOP_LOG, UOP_RE, UOP_IM, UOP_NEG, UOP_SUM, UOP_DIFF };

#endif //_UNARYOPERATOR_H